import numpy as np
from scipy.optimize import minimize, Bounds, LinearConstraint, NonlinearConstraint
from .hvacModels import acLosses, lossesCost

def reactorPlacement(flag_x0, U_init, I_init, Y_init, Ug, Zg, PowfN_pu, QowfN_pu, Ztr, Ytr, Zpi1, Ypi1, Zpi2, Ypi2, Sbase,
                     Towf, Ce, Koff, Poff, Kmid, Pmid, Kon, Pon, Vmax, Vmin, thetamax, thetamin, Imax, Imin, Tan_QPmax, Tan_QPmin,
                     Ymax, Ymin, pw, reac_comb, Closs_max, Creac_max, n_w, n_Y, wl, wr):
    """
    Calculate the optimal admittance of the reactors combination with Trust-Constr Method
    :param flag_x0: boolean information for the strategy of x0 initialization
    :param U_init, I_init, Y_init: voltage, current, and reactor admittance that satisfy the problem constraints for x0  
    :param Ug: Equivalent thevenin reference voltage of onshore grid 
    :param Zg: Equivalent thevenin impedance of onshore grid
    :param PowfN_pu: active power generated by the OWPP in pu
    :param QowfN_pu: reactive power generated by the OWPP in pu
    :param Ztr: impedance of transformer in pu
    :param Ytr: admitance of transformer in pu
    :param Zpi1 and Zpi2: impedance of line in pi model before and after mid-cable in pu
    :param Ypi1 and Ypi2: admitance of line in pi model in pu    
    :param Sbase: base power value in MVA
    :param Towf: life time of the WOPP in years 
    :param Ce: cost of energy in u.m./MWh
    :param Koff, Kmid, Kon, Poff, Pmid, Pon: cost coefficients for offshore, mid-cable, and onshore reactors
    :param Vmax, Vmin, thetamax, thetamin, Imax, Imin, Tan_QPmax, Tan_QPmin, Ymax, Ymin: constraints limit for voltage, angle, current, power factor at the PAC, and reactor
    :param pw: probability occurrence of generated active power
    :param reac_comb: reactor combination under evaluation
    :param Closs_max, Creac_max: maximum value to active power losses and reactor placed
    :param n_w: quantity of active power generation points to evaluate
    :param n_Y: quantity of reactors to be aallocated
    :param wl, wr: weighs of the objective function
    :return result, n_xj: optimization results, length of x vector for each n_w
    """   
    
    lb_reac = np.ones(n_Y) * Ymin    
    ub_reac = np.ones(n_Y) * Ymax
    
    lb_form = np.array([Vmin, thetamin, Vmin, thetamin, Vmin, thetamin, Vmin, thetamin, Vmin, thetamin,
                       Imin[0,0], thetamin, Imin[0,1], thetamin, Imin[0,2], thetamin, Imin[0,3], thetamin, Imin[0,4], thetamin,
                       Imin[0,5], thetamin])
    
    ub_form = np.array([Vmax, thetamax, Vmax, thetamax, Vmax, thetamax, Vmax, thetamax, Vmax, thetamax,
                   Imax[0,0], thetamax, Imax[0,1], thetamax, Imax[0,2], thetamax, Imax[0,3], thetamax, Imax[0,4], thetamax,
                   Imax[0,5], thetamax])
    
    lb_form = np.hstack((lb_form, lb_reac))    
    ub_form = np.hstack((ub_form, ub_reac))        
           
    n_xj = len(lb_form)   
    
    if n_w == 1:
        LB = lb_form.copy()
        UB = ub_form.copy()   
        if flag_x0:
            x0_base = np.array([np.abs(U_init[0]), np.angle(U_init[0]), np.abs(U_init[1]), np.angle(U_init[1]),
                            np.abs(U_init[2]), np.angle(U_init[2]), np.abs(U_init[3]), np.angle(U_init[3]),
                            np.abs(U_init[4]), np.angle(U_init[4]), np.abs(I_init[0]), np.angle(I_init[0]),
                            np.abs(I_init[1]), np.angle(I_init[1]), np.abs(I_init[2]), np.angle(I_init[2]),
                            np.abs(I_init[3]), np.angle(I_init[3]), np.abs(I_init[4]), np.angle(I_init[4]),
                            np.abs(I_init[5]), np.angle(I_init[5])])
            x0 = np.hstack((x0_base, np.imag(Y_init[0,reac_comb])))               
    else:
        for n_Pg in range(n_w):
            
            if n_Pg == 0:
                LB = lb_form.copy()
                UB = ub_form.copy()
                if flag_x0:
                    x0_base = np.array([np.abs(U_init[n_Pg,0]), np.angle(U_init[n_Pg,0]), np.abs(U_init[n_Pg,1]), np.angle(U_init[n_Pg,1]),
                                np.abs(U_init[n_Pg,2]), np.angle(U_init[n_Pg,2]), np.abs(U_init[n_Pg,3]), np.angle(U_init[n_Pg,3]),
                                np.abs(U_init[n_Pg,4]), np.angle(U_init[n_Pg,4]), np.abs(I_init[n_Pg,0]), np.angle(I_init[n_Pg,0]),
                                np.abs(I_init[n_Pg,1]), np.angle(I_init[n_Pg,1]), np.abs(I_init[n_Pg,2]), np.angle(I_init[n_Pg,2]),
                                np.abs(I_init[n_Pg,3]), np.angle(I_init[n_Pg,3]), np.abs(I_init[n_Pg,4]), np.angle(I_init[n_Pg,4]),
                                np.abs(I_init[n_Pg,5]), np.angle(I_init[n_Pg,5])])  
                    x0 = np.hstack((x0_base, np.imag(Y_init[n_Pg,reac_comb])))
            else:
                LB = np.hstack((LB,lb_form))
                UB = np.hstack((UB,ub_form))
                if flag_x0:
                    x0_base = np.array([np.abs(U_init[n_Pg,0]), np.angle(U_init[n_Pg,0]), np.abs(U_init[n_Pg,1]), np.angle(U_init[n_Pg,1]),
                                    np.abs(U_init[n_Pg,2]), np.angle(U_init[n_Pg,2]), np.abs(U_init[n_Pg,3]), np.angle(U_init[n_Pg,3]),
                                    np.abs(U_init[n_Pg,4]), np.angle(U_init[n_Pg,4]), np.abs(I_init[n_Pg,0]), np.angle(I_init[n_Pg,0]),
                                    np.abs(I_init[n_Pg,1]), np.angle(I_init[n_Pg,1]), np.abs(I_init[n_Pg,2]), np.angle(I_init[n_Pg,2]),
                                    np.abs(I_init[n_Pg,3]), np.angle(I_init[n_Pg,3]), np.abs(I_init[n_Pg,4]), np.angle(I_init[n_Pg,4]),
                                    np.abs(I_init[n_Pg,5]), np.angle(I_init[n_Pg,5])])
                    x0 = np.hstack((x0,x0_base, np.imag(Y_init[n_Pg,reac_comb])))
        
    LB = np.hstack((LB,lb_reac))
    UB = np.hstack((UB,ub_reac))
    
    bounds = Bounds(LB, UB)
    
    if flag_x0:
        x0 = np.hstack((x0,np.min(np.imag(Y_init[0:,reac_comb]),0)))
    else:
        x0 = (bounds.lb + bounds.ub) / 2        
    
    linear_constraint = Lconstraints(Vmin, Vmax, Imin, Imax, Ymin, Ymax, n_w, n_xj, n_Y)
       
    NLCLB = np.zeros((11*n_w*2+1*n_w,))
    NLCUB = NLCLB.copy()
    
    NLCLB[-n_w:] = Tan_QPmin
    NLCUB[-n_w:] = Tan_QPmax
    
    nonlinear_constraint = NonlinearConstraint(lambda x: NLconstraints(x, Ug, Zg, PowfN_pu, QowfN_pu, Ztr, Ytr, Zpi1, Ypi1, Zpi2, Ypi2, reac_comb, n_w, n_xj, n_Y), NLCLB, NLCUB, jac=lambda x:nl_jac(x, Zg, Ztr, Ytr, Zpi1, Ypi1, Zpi2, Ypi2, reac_comb, n_w, n_xj, n_Y), hess=lambda x,v:nl_hess(x, v, Zg, Ztr, Ytr, Zpi1, Ypi1, Zpi2, Ypi2, reac_comb, n_w, n_xj, n_Y))
    
    args_of = (PowfN_pu, Sbase, Towf, Ce, Koff, Poff, Kmid, Pmid, Kon, Pon, reac_comb, pw, Closs_max, Creac_max, wl, wr, n_w, n_xj, n_Y)
    
    result = minimize(objective_function, x0, 
    args=args_of, 
    method='trust-constr',
    jac=of_jac,
    hess=of_hess,
    bounds=bounds,
    constraints=[linear_constraint, nonlinear_constraint],
    options={'verbose': 0, 'maxiter': 500, 'sparse_jacobian':True})
    
    flag_x0_success = 0
    if flag_x0:
        if not result.success:
            flag_x0_success = 1
            x0 = (bounds.lb + bounds.ub) / 2
            result = minimize(objective_function, x0, 
            args=args_of, 
            method='trust-constr',
            jac=of_jac,
            hess=of_hess,
            bounds=bounds,
            constraints=[linear_constraint, nonlinear_constraint],
            options={'verbose': 0, 'maxiter': 500, 'sparse_jacobian':True})
        else:
            flag_x0_success = 2
            
    return result, n_xj, flag_x0_success

def Lconstraints(Vmin, Vmax, Imin, Imax, Ymin, Ymax, n_w, n_xj, n_Y):
    """
    Calculate the linear constraints of the problem and its limit
    :param Vmax, Vmin, Imax, Imin, Ymax, Ymin: constraints limit for voltage, current, and reactor
    :param n_w: quantity of active power generation points to evaluate
    :param n_Y: quantity of reactors to be aallocated
    :param n_xj: length of x vector for each n_w
    :return linearConstraint: python object with the linear constraint values
    """   
    n_eq = 11 + n_Y
    if n_Y == 1:
        lclb_form = np.array([Vmin, Vmin, Vmin, Vmin, Vmin, Imin[0,0], Imin[0,1], Imin[0,2], Imin[0,3], Imin[0,4], Imin[0,5], Ymin])
        lcub_form = np.array([Vmax, Vmax, Vmax, Vmax, Vmax, Imax[0,0], Imax[0,1], Imax[0,2], Imax[0,3], Imax[0,4], Imax[0,5], Ymax])
    elif n_Y == 2:
        lclb_form = np.array([Vmin, Vmin, Vmin, Vmin, Vmin, Imin[0,0], Imin[0,1], Imin[0,2], Imin[0,3], Imin[0,4], Imin[0,5], Ymin, Ymin])
        lcub_form = np.array([Vmax, Vmax, Vmax, Vmax, Vmax, Imax[0,0], Imax[0,1], Imax[0,2], Imax[0,3], Imax[0,4], Imax[0,5], Ymax, Ymax])
    elif n_Y == 3:
        lclb_form = np.array([Vmin, Vmin, Vmin, Vmin, Vmin, Imin[0,0], Imin[0,1], Imin[0,2], Imin[0,3], Imin[0,4], Imin[0,5], Ymin, Ymin, Ymin])
        lcub_form = np.array([Vmax, Vmax, Vmax, Vmax, Vmax, Imax[0,0], Imax[0,1], Imax[0,2], Imax[0,3], Imax[0,4], Imax[0,5], Ymax, Ymax, Ymax])
    elif n_Y == 4:
        lclb_form = np.array([Vmin, Vmin, Vmin, Vmin, Vmin, Imin[0,0], Imin[0,1], Imin[0,2], Imin[0,3], Imin[0,4], Imin[0,5], Ymin, Ymin, Ymin, Ymin])
        lcub_form = np.array([Vmax, Vmax, Vmax, Vmax, Vmax, Imax[0,0], Imax[0,1], Imax[0,2], Imax[0,3], Imax[0,4], Imax[0,5], Ymax, Ymax, Ymax, Ymax])
    elif n_Y == 5:
        lclb_form = np.array([Vmin, Vmin, Vmin, Vmin, Vmin, Imin[0,0], Imin[0,1], Imin[0,2], Imin[0,3], Imin[0,4], Imin[0,5], Ymin, Ymin, Ymin, Ymin, Ymin])
        lcub_form = np.array([Vmax, Vmax, Vmax, Vmax, Vmax, Imax[0,0], Imax[0,1], Imax[0,2], Imax[0,3], Imax[0,4], Imax[0,5], Ymax, Ymax, Ymax, Ymax, Ymax])    
    
    
    A = np.zeros((n_eq*n_w,(n_xj*n_w)+n_Y))
    for i in range(n_w):
        A[0+n_eq*i,0+n_xj*i] = 1
        A[1+n_eq*i,2+n_xj*i] = 1
        A[2+n_eq*i,4+n_xj*i] = 1
        A[3+n_eq*i,6+n_xj*i] = 1
        A[4+n_eq*i,8+n_xj*i] = 1
        A[5+n_eq*i,10+n_xj*i] = 1
        A[6+n_eq*i,12+n_xj*i] = 1
        A[7+n_eq*i,14+n_xj*i] = 1
        A[8+n_eq*i,16+n_xj*i] = 1
        A[9+n_eq*i,18+n_xj*i] = 1
        A[10+n_eq*i,20+n_xj*i] = 1
        A[11+n_eq*i,22+n_xj*i] = -1
        A[11+n_eq*i,-n_Y] = 1
        if n_Y > 1:
            A[12+n_eq*i,23+n_xj*i] = -1
            A[12+n_eq*i,-n_Y+1] = 1
        if n_Y > 2:
            A[13+n_eq*i,24+n_xj*i] = -1
            A[13+n_eq*i,-n_Y+2] = 1
        if n_Y > 3:
            A[14+n_eq*i,25+n_xj*i] = -1
            A[14+n_eq*i,-n_Y+3] = 1
        if n_Y > 4:
            A[15+n_eq*i,26+n_xj*i] = -1
            A[15+n_eq*i,-n_Y+4] = 1
    
        if i == 0:
            LCLB = lclb_form.copy()
            LCUB = lcub_form.copy()  
        else:
            LCLB = np.hstack((LCLB,lclb_form))
            LCUB = np.hstack((LCUB,lcub_form))               
            
    return LinearConstraint(A, LCLB, LCUB)

def NLconstraints(x, Ug, Zg, PowfN_pu, QowfN_pu, Ztr, Ytr, Zpi1, Ypi1, Zpi2, Ypi2, reac_comb, n_w, n_xj, n_Y):
    """
    Calculate the vector with the non-linear constraints value
    :param x: vector of the variables solution
    :param Ug: Equivalent thevenin reference voltage of onshore grid 
    :param Zg: Equivalent thevenin impedance of onshore grid
    :param PowfN_pu: active power generated by the OWPP in pu
    :param QowfN_pu: reactive power generated by the OWPP in pu
    :param Ztr: impedance of transformer in pu
    :param Ytr: admitance of transformer in pu
    :param Zpi1 and Zpi2: impedance of line in pi model before and after mid-cable in pu
    :param Ypi1 and Ypi2: admitance of line in pi model in pu    
    :param reac_comb: reactor combination under evaluation
    :param n_w: quantity of active power generation points to evaluate
    :param n_Y: quantity of reactors to be aallocated
    :param n_xj: length of x vector for each n_w
    :return nl_matrix: vector with the non-linear constraints result
    """   
    Umod, Utheta, Imod, Itheta, Yl_x, Yreac_x = identify_x(x, n_w, n_xj, n_Y)
    
    Yl = np.zeros((n_w, len(reac_comb)))
    Yl[0:,reac_comb] = Yl_x
    
    Yl1 = Yl[0:,0] * 1j
    Yl2 = Yl[0:,1] * 1j
    Yl3 = Yl[0:,2] * 1j
    Yl4 = Yl[0:,3] * 1j
    Yl5 = Yl[0:,4] * 1j
    U1 = Umod[0:,0] * np.exp(Utheta[0:,0] * 1j)
    U2 = Umod[0:,1] * np.exp(Utheta[0:,1] * 1j)
    U3 = Umod[0:,2] * np.exp(Utheta[0:,2] * 1j)
    U4 = Umod[0:,3] * np.exp(Utheta[0:,3] * 1j)
    U5 = Umod[0:,4] * np.exp(Utheta[0:,4] * 1j)
    I1 = Imod[0:,0] * np.exp(Itheta[0:,0] * 1j)
    I2 = Imod[0:,1] * np.exp(Itheta[0:,1] * 1j)
    I3 = Imod[0:,2] * np.exp(Itheta[0:,2] * 1j)
    I4 = Imod[0:,3] * np.exp(Itheta[0:,3] * 1j)
    I5 = Imod[0:,4] * np.exp(Itheta[0:,4] * 1j)
    Ig = Imod[0:,5] * np.exp(Itheta[0:,5] * 1j)
    
    UG = np.ones((n_w)) * Ug
    
    nl_matrix = np.hstack((U1 * np.conj(I1) - (PowfN_pu + QowfN_pu * 1j),
                            U1 - U2 - Ztr * I2,
                            I1 - I2 - (Ytr + Yl1) * U1,
                            U2 - U3 - Zpi1 * I3,
                            I2 - I3 - (Ypi1 + Yl2) * U2,
                            I3 - I4 - (Ypi1 + Yl3 + Ypi2) * U3,
                            U3 - U4 - Zpi2 * I4,
                            I4 - I5 - (Ypi2 + Yl4) * U4,
                            U4 - U5 - Ztr * I5,
                            I5 - Ig - (Ytr + Yl5) * U5,
                            U5 - UG - Zg * Ig))

    
    nl_matrix = nl_matrix.view(np.double)
    
    nl_matrix = np.hstack((nl_matrix, (np.imag(U5 * np.conj(Ig))/np.real(U5 * np.conj(Ig)))))
    
    return nl_matrix

def nl_jac(x, Zg, Ztr, Ytr, Zpi1, Ypi1, Zpi2, Ypi2, reac_comb, n_w, n_xj, n_Y):
    """
    Calculate the jacobian matrix with the partial derivative values of the non-linear constraints
    :param x: vector of the variables solution
    :param Zg: Equivalent thevenin impedance of onshore grid
    :param Ztr: impedance of transformer in pu
    :param Ytr: admitance of transformer in pu
    :param Zpi1 and Zpi2: impedance of line in pi model before and after mid-cable in pu
    :param Ypi1 and Ypi2: admitance of line in pi model in pu    
    :param reac_comb: reactor combination under evaluation
    :param n_w: quantity of active power generation points to evaluate
    :param n_Y: quantity of reactors to be aallocated
    :param n_xj: length of x vector for each n_w
    :return nl_jac: jacobian matrix of the non-linear constraints
    """ 
    Umod, Utheta, Imod, Itheta, Yl_x, Yreac_x = identify_x(x, n_w, n_xj, n_Y)  
    Yl = np.zeros((n_w, len(reac_comb)))
    Yl[0:,reac_comb] = Yl_x
    Yl1 = Yl[0:,0]
    Yl2 = Yl[0:,1]
    Yl3 = Yl[0:,2]
    Yl4 = Yl[0:,3]
    Yl5 = Yl[0:,4]
    
    nl_jac = np.zeros((n_w*11,len(x)), dtype = complex)
    c12_jac = np.zeros((n_w,len(x)))
    for i in range(n_w):        
        # Restrição C1(x)
        nl_jac[0*n_w+i,0+n_xj*i] = x[10+n_xj*i]*np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        nl_jac[0*n_w+i,1+n_xj*i] = 1j * x[0+n_xj*i] * x[10+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i]))
        nl_jac[0*n_w+i,10+n_xj*i] = x[0+n_xj*i]*np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        nl_jac[0*n_w+i,11+n_xj*i] = -1j * x[0+n_xj*i] * x[10+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i]))
        
        # Restrição C2(x)
        nl_jac[1*n_w+i,0+n_xj*i] = np.exp(1j*x[1+n_xj*i])
        nl_jac[1*n_w+i,1+n_xj*i] = 1j * x[0+n_xj*i] * np.exp(1j*x[1+n_xj*i]) 
        nl_jac[1*n_w+i,2+n_xj*i] = -np.exp(1j*x[3+n_xj*i])  
        nl_jac[1*n_w+i,3+n_xj*i] = -1j * x[2+n_xj*i] * np.exp(1j*x[3+n_xj*i])
        nl_jac[1*n_w+i,12+n_xj*i] = -Ztr * np.exp(1j*x[13+n_xj*i])
        nl_jac[1*n_w+i,13+n_xj*i] = -1j * Ztr * x[12+n_xj*i] * np.exp(1j*x[13+n_xj*i])
        
        # Restrição C3(x)
        nl_jac[2*n_w+i,0+n_xj*i] = -(Ytr + Yl1[i]*1j) * np.exp(1j*x[1+n_xj*i])
        nl_jac[2*n_w+i,1+n_xj*i] = -1j*(Ytr + Yl1[i]*1j) * x[0+n_xj*i] * np.exp(1j*x[1+n_xj*i]) 
        nl_jac[2*n_w+i,10+n_xj*i] = np.exp(1j*x[11+n_xj*i]) 
        nl_jac[2*n_w+i,11+n_xj*i] = 1j * x[10+n_xj*i] * np.exp(1j*x[11+n_xj*i])
        nl_jac[2*n_w+i,12+n_xj*i] = -np.exp(1j*x[13+n_xj*i])  
        nl_jac[2*n_w+i,13+n_xj*i] = -1j * x[12+n_xj*i] * np.exp(1j*x[13+n_xj*i])
        if reac_comb[0]:
            nl_jac[2*n_w+i,22+n_xj*i] = -1j * x[0+n_xj*i] * np.exp(1j*x[1+n_xj*i]) 
       
        # Restrição C4(x)
        nl_jac[3*n_w+i,2+n_xj*i] = np.exp(1j*x[3+n_xj*i])
        nl_jac[3*n_w+i,3+n_xj*i] = 1j * x[2+n_xj*i] * np.exp(1j*x[3+n_xj*i]) 
        nl_jac[3*n_w+i,4+n_xj*i] = -np.exp(1j*x[5+n_xj*i])  
        nl_jac[3*n_w+i,5+n_xj*i] = -1j * x[4+n_xj*i] * np.exp(1j*x[5+n_xj*i])
        nl_jac[3*n_w+i,14+n_xj*i] = -Zpi1 * np.exp(1j*x[15+n_xj*i])
        nl_jac[3*n_w+i,15+n_xj*i] = -1j * Zpi1 * x[14+n_xj*i] * np.exp(1j*x[15+n_xj*i])
      
        # Restrição C5(x)
        nl_jac[4*n_w+i,2+n_xj*i] = -(Ypi1 + Yl2[i]*1j) * np.exp(1j*x[3+n_xj*i])
        nl_jac[4*n_w+i,3+n_xj*i] = -1j*(Ypi1 + Yl2[i]*1j) * x[2+n_xj*i] * np.exp(1j*x[3+n_xj*i]) 
        nl_jac[4*n_w+i,12+n_xj*i] = np.exp(1j*x[13+n_xj*i])  
        nl_jac[4*n_w+i,13+n_xj*i] = 1j * x[12+n_xj*i] * np.exp(1j*x[13+n_xj*i])
        nl_jac[4*n_w+i,14+n_xj*i] = -np.exp(1j*x[15+n_xj*i]) 
        nl_jac[4*n_w+i,15+n_xj*i] = -1j * x[14+n_xj*i] * np.exp(1j*x[15+n_xj*i])      
        if reac_comb[0] and reac_comb[1]:
            nl_jac[4*n_w+i,23+n_xj*i] = -1j * x[2+n_xj*i] * np.exp(1j*x[3+n_xj*i]) 
        elif reac_comb[1]:
            nl_jac[4*n_w+i,22+n_xj*i] = -1j * x[2+n_xj*i] * np.exp(1j*x[3+n_xj*i]) 
        
        # Restrição C6(x)    
        nl_jac[5*n_w+i,4+n_xj*i] = -(Ypi1 + Yl3[i]*1j + Ypi2) * np.exp(1j*x[5+n_xj*i]) 
        nl_jac[5*n_w+i,5+n_xj*i] = -1j*(Ypi1 + Yl3[i]*1j + Ypi2) * x[4+n_xj*i] * np.exp(1j*x[5+n_xj*i]) 
        nl_jac[5*n_w+i,14+n_xj*i] = np.exp(1j*x[15+n_xj*i])
        nl_jac[5*n_w+i,15+n_xj*i] = 1j * x[14+n_xj*i] * np.exp(1j*x[15+n_xj*i])
        nl_jac[5*n_w+i,16+n_xj*i] = -np.exp(1j*x[17+n_xj*i]) 
        nl_jac[5*n_w+i,17+n_xj*i] = -1j * x[16+n_xj*i] * np.exp(1j*x[17+n_xj*i])        
        if reac_comb[0] and reac_comb[1] and reac_comb[2]:
            nl_jac[5*n_w+i,24+n_xj*i] = -1j * x[4+n_xj*i] * np.exp(1j*x[5+n_xj*i])
        elif (reac_comb[2] and reac_comb[1]) or (reac_comb[2] and reac_comb[0]):
            nl_jac[5*n_w+i,23+n_xj*i] = -1j * x[4+n_xj*i] * np.exp(1j*x[5+n_xj*i]) 
        elif reac_comb[2]:
            nl_jac[5*n_w+i,22+n_xj*i] = -1j * x[4+n_xj*i] * np.exp(1j*x[5+n_xj*i]) 
       
        # Restrição C7(x)
        nl_jac[6*n_w+i,4+n_xj*i] = np.exp(1j*x[5+n_xj*i]) 
        nl_jac[6*n_w+i,5+n_xj*i] = 1j * x[4+n_xj*i] * np.exp(1j*x[5+n_xj*i]) 
        nl_jac[6*n_w+i,6+n_xj*i] = -np.exp(1j*x[7+n_xj*i])  
        nl_jac[6*n_w+i,7+n_xj*i] = -1j * x[6+n_xj*i] * np.exp(1j*x[7+n_xj*i])
        nl_jac[6*n_w+i,16+n_xj*i] = -Zpi2 * np.exp(1j*x[17+n_xj*i])
        nl_jac[6*n_w+i,17+n_xj*i] = -1j * Zpi2 * x[16+n_xj*i] * np.exp(1j*x[17+n_xj*i])
       
        # Restrição C8(x)    
        nl_jac[7*n_w+i,6+n_xj*i] = -(Ypi2 + Yl4[i]*1j) * np.exp(1j*x[7+n_xj*i]) 
        nl_jac[7*n_w+i,7+n_xj*i] = -1j*(Ypi2 + Yl4[i]*1j) * x[6+n_xj*i] * np.exp(1j*x[7+n_xj*i]) 
        nl_jac[7*n_w+i,16+n_xj*i] = np.exp(1j*x[17+n_xj*i])
        nl_jac[7*n_w+i,17+n_xj*i] = 1j * x[16+n_xj*i] * np.exp(1j*x[17+n_xj*i])
        nl_jac[7*n_w+i,18+n_xj*i] = -np.exp(1j*x[19+n_xj*i]) 
        nl_jac[7*n_w+i,19+n_xj*i] = -1j * x[18+n_xj*i] * np.exp(1j*x[19+n_xj*i])       
        if reac_comb[0] and reac_comb[1] and reac_comb[2] and reac_comb[3]:
            nl_jac[7*n_w+i,25+n_xj*i] = -1j * x[6+n_xj*i] * np.exp(1j*x[7+n_xj*i])
        elif (reac_comb[3] and reac_comb[0] and reac_comb[1]) or (reac_comb[3] and reac_comb[0] and reac_comb[2]) or (reac_comb[3] and reac_comb[1] and reac_comb[2]):
            nl_jac[7*n_w+i,24+n_xj*i] = -1j * x[6+n_xj*i] * np.exp(1j*x[7+n_xj*i])
        elif (reac_comb[3] and reac_comb[2]) or (reac_comb[3] and reac_comb[1]) or (reac_comb[3] and reac_comb[0]):
            nl_jac[7*n_w+i,23+n_xj*i] = -1j * x[6+n_xj*i] * np.exp(1j*x[7+n_xj*i])
        elif reac_comb[3]:
            nl_jac[7*n_w+i,22+n_xj*i] = -1j * x[6+n_xj*i] * np.exp(1j*x[7+n_xj*i])
            
        # Restrição C9(x)
        nl_jac[8*n_w+i,6+n_xj*i] = np.exp(1j*x[7+n_xj*i]) 
        nl_jac[8*n_w+i,7+n_xj*i] = 1j * x[6+n_xj*i] * np.exp(1j*x[7+n_xj*i]) 
        nl_jac[8*n_w+i,8+n_xj*i] = -np.exp(1j*x[9+n_xj*i]) 
        nl_jac[8*n_w+i,9+n_xj*i] = -1j * x[8+n_xj*i] * np.exp(1j*x[9+n_xj*i])
        nl_jac[8*n_w+i,18+n_xj*i] = -Ztr * np.exp(1j*x[19+n_xj*i]) 
        nl_jac[8*n_w+i,19+n_xj*i] = -1j * Ztr * x[18+n_xj*i] * np.exp(1j*x[19+n_xj*i])
        
        # Restrição C10(x)    
        nl_jac[9*n_w+i,8+n_xj*i] = -(Ytr + Yl5[i]*1j) * np.exp(1j*x[9+n_xj*i]) 
        nl_jac[9*n_w+i,9+n_xj*i] = -1j*(Ytr + Yl5[i]*1j) * x[8+n_xj*i] * np.exp(1j*x[9+n_xj*i]) 
        nl_jac[9*n_w+i,18+n_xj*i] = np.exp(1j*x[19+n_xj*i])  
        nl_jac[9*n_w+i,19+n_xj*i] = 1j * x[18+n_xj*i] * np.exp(1j*x[19+n_xj*i])
        nl_jac[9*n_w+i,20+n_xj*i] = -np.exp(1j*x[21+n_xj*i]) 
        nl_jac[9*n_w+i,21+n_xj*i] = -1j * x[20+n_xj*i] * np.exp(1j*x[21+n_xj*i])        
        if reac_comb[0] and reac_comb[1] and reac_comb[2] and reac_comb[3] and reac_comb[4]:
            nl_jac[9*n_w+i,26+n_xj*i] = -1j * x[8+n_xj*i] * np.exp(1j*x[9+n_xj*i])
        elif (reac_comb[4] and reac_comb[0] and reac_comb[1] and reac_comb[2]) or (reac_comb[4] and reac_comb[0] and reac_comb[1] and reac_comb[3]) or (reac_comb[4] and reac_comb[0] and reac_comb[2] and reac_comb[3]) or (reac_comb[4] and reac_comb[1] and reac_comb[2] and reac_comb[3]):
            nl_jac[9*n_w+i,25+n_xj*i] = -1j * x[8+n_xj*i] * np.exp(1j*x[9+n_xj*i])
        elif (reac_comb[4] and reac_comb[0] and reac_comb[1]) or (reac_comb[4] and reac_comb[0] and reac_comb[2]) or (reac_comb[4] and reac_comb[0] and reac_comb[3]) or (reac_comb[4] and reac_comb[1] and reac_comb[2]) or (reac_comb[4] and reac_comb[1] and reac_comb[3]) or (reac_comb[4] and reac_comb[2] and reac_comb[3]):
            nl_jac[9*n_w+i,24+n_xj*i] = -1j * x[8+n_xj*i] * np.exp(1j*x[9+n_xj*i])
        elif (reac_comb[4] and reac_comb[3]) or (reac_comb[4] and reac_comb[2]) or (reac_comb[4] and reac_comb[1])  or (reac_comb[4] and reac_comb[0]):
            nl_jac[9*n_w+i,23+n_xj*i] = -1j * x[8+n_xj*i] * np.exp(1j*x[9+n_xj*i])
        elif reac_comb[4]:
            nl_jac[9*n_w+i,22+n_xj*i] = -1j * x[8+n_xj*i] * np.exp(1j*x[9+n_xj*i])
        
        # Restrição C11(x)
        nl_jac[10*n_w+i,8+n_xj*i] = np.exp(1j*x[9+n_xj*i]) 
        nl_jac[10*n_w+i,9+n_xj*i] = 1j * x[8+n_xj*i] * np.exp(1j*x[9+n_xj*i]) 
        nl_jac[10*n_w+i,20+n_xj*i] = -Zg * np.exp(1j*x[21+n_xj*i])  
        nl_jac[10*n_w+i,21+n_xj*i] = -1j * Zg * x[20+n_xj*i] * np.exp(1j*x[21+n_xj*i])
        
        # Restrição C12(x)
        c12_jac[0+i,9+n_xj*i] = (1/np.cos(x[9+n_xj*i]-x[21+n_xj*i]))**2 
        c12_jac[0+i,21+n_xj*i] = -(1/np.cos(x[9+n_xj*i]-x[21+n_xj*i]))**2 
           
    R_part = np.real(nl_jac)
    I_part = np.imag(nl_jac)
    
    nl_jac = np.zeros((len(nl_jac)*2,len(x)))
    for i in range(len(R_part)):
        nl_jac[0+2*i,:] = R_part[i,:]
        nl_jac[1+2*i,:] = I_part[i,:]
    
    nl_jac = np.concatenate((nl_jac,c12_jac))
           
    return nl_jac

def nl_hess(x, v, Zg, Ztr, Ytr, Zpi1, Ypi1, Zpi2, Ypi2, reac_comb, n_w, n_xj, n_Y):    
    """
    Calculate the hessian matrix with the second ordem partial derivative values of the non-linear constraints
    :param x: vector of the variables solution
    :param v: vector from the Trust-Constr method
    :param Zg: Equivalent thevenin impedance of onshore grid
    :param Ztr: impedance of transformer in pu
    :param Ytr: admitance of transformer in pu
    :param Zpi1 and Zpi2: impedance of line in pi model before and after mid-cable in pu
    :param Ypi1 and Ypi2: admitance of line in pi model in pu    
    :param reac_comb: reactor combination under evaluation
    :param n_w: quantity of active power generation points to evaluate
    :param n_Y: quantity of reactors to be aallocated
    :param n_xj: length of x vector for each n_w
    :return nl_hess: hessian matrix of the non-linear constraints
    """     
    def Hess_C1(x, i, n_xj):
        hess = np.zeros((len(x),len(x)), dtype = complex)
        
        hess[0+n_xj*i,1+n_xj*i] = 1j * x[10+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        hess[0+n_xj*i,10+n_xj*i] = np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i]))
        hess[0+n_xj*i,11+n_xj*i] = -1j * x[10+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        hess[1+n_xj*i,0+n_xj*i] = 1j * x[10+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        hess[1+n_xj*i,1+n_xj*i] = -x[0+n_xj*i] *  x[10+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        hess[1+n_xj*i,10+n_xj*i] = 1j * x[0+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        hess[1+n_xj*i,11+n_xj*i] = x[0+n_xj*i] *  x[10+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i]))    
        hess[10+n_xj*i,0+n_xj*i] = np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i]))
        hess[10+n_xj*i,1+n_xj*i] = 1j * x[0+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        hess[10+n_xj*i,11+n_xj*i] = -1j * x[0+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        hess[11+n_xj*i,0+n_xj*i] = -1j * x[10+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        hess[11+n_xj*i,1+n_xj*i] = x[0+n_xj*i] *  x[10+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        hess[11+n_xj*i,10+n_xj*i] = -1j * x[0+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        hess[11+n_xj*i,11+n_xj*i] = -x[0+n_xj*i] *  x[10+n_xj*i] * np.exp(1j*(x[1+n_xj*i]-x[11+n_xj*i])) 
        
        R_part = np.real(hess)
        I_part = np.imag(hess)
        return R_part, I_part
    
    def Hess_CV(x, i, n_xj, Z, Umod1, Uang1, Umod2, Uang2, Imod, Iang):
        hess = np.zeros((len(x),len(x)), dtype = complex)
        
        hess[Umod1+n_xj*i,Uang1+n_xj*i] = 1j * np.exp(1j*x[Uang1+n_xj*i]) 
        hess[Uang1+n_xj*i,Umod1+n_xj*i] = 1j * np.exp(1j*x[Uang1+n_xj*i])
        hess[Uang1+n_xj*i,Uang1+n_xj*i] = -x[Umod1+n_xj*i] * np.exp(1j*x[Uang1+n_xj*i])
        if (Umod2 != -1) and (Uang2 != -1):   
            hess[Umod2+n_xj*i,Uang2+n_xj*i] = -1j * np.exp(1j*x[Uang2+n_xj*i]) 
            hess[Uang2+n_xj*i,Umod2+n_xj*i] = -1j * np.exp(1j*x[Uang2+n_xj*i])
            hess[Uang2+n_xj*i,Uang2+n_xj*i] = x[Umod2+n_xj*i] * np.exp(1j*x[Uang2+n_xj*i])                        
        hess[Imod+n_xj*i,Iang+n_xj*i] = -1j * Z * np.exp(1j*x[Iang+n_xj*i])
        hess[Iang+n_xj*i,Imod+n_xj*i] = -1j * Z * np.exp(1j*x[Iang+n_xj*i]) 
        hess[Iang+n_xj*i,Iang+n_xj*i] = x[Imod+n_xj*i] * Z * np.exp(1j*x[Iang+n_xj*i]) 

        R_part = np.real(hess)
        I_part = np.imag(hess)
        return R_part, I_part
    
    def Hess_CI(x, i, n_xj, Y, Yl, reac, Umod, Uang, Imod1, Iang1, Imod2, Iang2, ind_reac):
        hess = np.zeros((len(x),len(x)), dtype = complex)
        
        hess[Umod+n_xj*i,Uang+n_xj*i] = -1j * (Y+1j*Yl) * np.exp(1j*x[Uang+n_xj*i])
        if reac:
            hess[Umod+n_xj*i,ind_reac+n_xj*i] = -1j * np.exp(1j*x[Uang+n_xj*i])
        
        hess[Uang+n_xj*i,Umod+n_xj*i] = -1j * (Y+1j*Yl) * np.exp(1j*x[Uang+n_xj*i])
        hess[Uang+n_xj*i,Uang+n_xj*i] = (Y+1j*Yl) * x[Umod+n_xj*i] * np.exp(1j*x[Uang+n_xj*i])
        if reac:
            hess[Uang+n_xj*i,ind_reac+n_xj*i] =  x[Umod+n_xj*i] * np.exp(1j*x[Uang+n_xj*i])
        
        hess[Imod1+n_xj*i,Iang1+n_xj*i] = 1j * np.exp(1j*x[Iang1+n_xj*i])
        hess[Iang1+n_xj*i,Imod1+n_xj*i] = 1j * np.exp(1j*x[Iang1+n_xj*i]) 
        hess[Iang1+n_xj*i,Iang1+n_xj*i] = -x[Imod1+n_xj*i] * np.exp(1j*x[Iang1+n_xj*i]) 
        
        hess[Imod2+n_xj*i,Iang2+n_xj*i] = -1j * np.exp(1j*x[Iang2+n_xj*i])
        hess[Iang2+n_xj*i,Imod2+n_xj*i] = -1j * np.exp(1j*x[Iang2+n_xj*i]) 
        hess[Iang2+n_xj*i,Iang2+n_xj*i] = x[Imod2+n_xj*i] * np.exp(1j*x[Iang2+n_xj*i])
        
        if reac:
            hess[ind_reac+n_xj*i,Umod+n_xj*i] = -1j * np.exp(1j*x[Uang+n_xj*i])
            hess[ind_reac+n_xj*i,Uang+n_xj*i] = x[Umod+n_xj*i]* np.exp(1j*x[Uang+n_xj*i])
            
        R_part = np.real(hess)
        I_part = np.imag(hess)
        return R_part, I_part
    
    def Hess_C12(x, i, n_xj):
        hess = np.zeros((len(x),len(x)))        
        
        hess[9+n_xj*i,9+n_xj*i] = 2*np.tan(x[9+n_xj*i]-x[21+n_xj*i])*(1/np.cos(x[9+n_xj*i]-x[21+n_xj*i]))**2
        hess[9+n_xj*i,21+n_xj*i] = -2*np.tan(x[9+n_xj*i]-x[21+n_xj*i])*(1/np.cos(x[9+n_xj*i]-x[21+n_xj*i]))**2        
        hess[21+n_xj*i,9+n_xj*i] = -2*np.tan(x[9+n_xj*i]-x[21+n_xj*i])*(1/np.cos(x[9+n_xj*i]-x[21+n_xj*i]))**2  
        hess[21+n_xj*i,21+n_xj*i] = 2*np.tan(x[9+n_xj*i]-x[21+n_xj*i])*(1/np.cos(x[9+n_xj*i]-x[21+n_xj*i]))**2        
        return hess
    
    nl_hess = np.diag(np.zeros_like(x))
    
    Umod, Utheta, Imod, Itheta, Yl_x, Yreac_x = identify_x(x, n_w, n_xj, n_Y)  
    Yl = np.zeros((n_w, len(reac_comb)))
    Yl[0:,reac_comb] = Yl_x
    Yl1 = Yl[0:,0]
    Yl2 = Yl[0:,1]
    Yl3 = Yl[0:,2]
    Yl4 = Yl[0:,3]
    Yl5 = Yl[0:,4]
    
    if reac_comb[0]:
        ind_reac1 = 22
    else:
        ind_reac1 = 0
        
    if reac_comb[0] and reac_comb[1]:
        ind_reac2 = 23
    elif reac_comb[1]:
        ind_reac2 = 22
    else:
        ind_reac2 = 0
    
    if reac_comb[0] and reac_comb[1] and reac_comb[2]:
        ind_reac3 = 24
    elif (reac_comb[2] and reac_comb[1]) or (reac_comb[2] and reac_comb[0]):
        ind_reac3 = 23
    elif reac_comb[2]:
        ind_reac3 = 22
    else:
        ind_reac3 = 0
        
    if reac_comb[0] and reac_comb[1] and reac_comb[2] and reac_comb[3]:
        ind_reac4 = 25
    elif (reac_comb[3] and reac_comb[0] and reac_comb[1]) or (reac_comb[3] and reac_comb[0] and reac_comb[2]) or (reac_comb[3] and reac_comb[1] and reac_comb[2]):
        ind_reac4 = 24
    elif (reac_comb[3] and reac_comb[2]) or (reac_comb[3] and reac_comb[1]) or (reac_comb[3] and reac_comb[0]):
        ind_reac4 = 23
    elif reac_comb[3]:
        ind_reac4 = 22
    else:
        ind_reac4 = 0
    
    if reac_comb[0] and reac_comb[1] and reac_comb[2] and reac_comb[3] and reac_comb[4]:
        ind_reac5 = 26
    elif (reac_comb[4] and reac_comb[0] and reac_comb[1] and reac_comb[2]) or (reac_comb[4] and reac_comb[0] and reac_comb[1] and reac_comb[3]) or (reac_comb[4] and reac_comb[0] and reac_comb[2] and reac_comb[3]) or (reac_comb[4] and reac_comb[1] and reac_comb[2] and reac_comb[3]):
        ind_reac5 = 25
    elif (reac_comb[4] and reac_comb[0] and reac_comb[1]) or (reac_comb[4] and reac_comb[0] and reac_comb[2]) or (reac_comb[4] and reac_comb[0] and reac_comb[3]) or (reac_comb[4] and reac_comb[1] and reac_comb[2]) or (reac_comb[4] and reac_comb[1] and reac_comb[3]) or (reac_comb[4] and reac_comb[2] and reac_comb[3]):
        ind_reac5 = 24
    elif (reac_comb[4] and reac_comb[3]) or (reac_comb[4] and reac_comb[2]) or (reac_comb[4] and reac_comb[1])  or (reac_comb[4] and reac_comb[0]):
        ind_reac5 = 23
    elif reac_comb[4]:
        ind_reac5 = 22
    else:
        ind_reac5 = 0
    
    for i in range(n_w):
        # Derivadas parciais jacobiana da restrição C1(x)
        H_real, H_imag = Hess_C1(x, i, n_xj)
        nl_hess = nl_hess + v[0+2*i] * H_real + v[1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C2(x)
        H_real, H_imag = Hess_CV(x, i, n_xj, Ztr, 0, 1, 2, 3, 12, 13)
        nl_hess = nl_hess + v[2*n_w+2*i] * H_real + v[2*n_w+1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C3(x)
        H_real, H_imag = Hess_CI(x, i, n_xj, Ytr, Yl1[i], reac_comb[0], 0, 1, 10, 11, 12, 13, ind_reac1)
        nl_hess = nl_hess + v[4*n_w+2*i] * H_real + v[4*n_w+1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C4(x)
        H_real, H_imag = Hess_CV(x, i, n_xj, Zpi1, 2, 3, 4, 5, 14, 15)
        nl_hess = nl_hess + v[6*n_w+2*i] * H_real + v[6*n_w+1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C5(x)
        H_real, H_imag = Hess_CI(x, i, n_xj, Ypi1, Yl2[i], reac_comb[1], 2, 3, 12, 13, 14, 15, ind_reac2)
        nl_hess = nl_hess + v[8*n_w+2*i] * H_real + v[8*n_w+1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C6(x)
        H_real, H_imag = Hess_CI(x, i, n_xj, (Ypi1+Ypi2), Yl3[i], reac_comb[2], 4, 5, 14, 15, 16, 17, ind_reac3)
        nl_hess = nl_hess + v[10*n_w+2*i] * H_real + v[10*n_w+1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C7(x)
        H_real, H_imag = Hess_CV(x, i, n_xj, Zpi2, 4, 5, 6, 7, 16, 17)
        nl_hess = nl_hess + v[12*n_w+2*i] * H_real + v[12*n_w+1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C8(x)
        H_real, H_imag = Hess_CI(x, i, n_xj, Ypi2, Yl4[i], reac_comb[3], 6, 7, 16, 17, 18, 19, ind_reac4)
        nl_hess = nl_hess + v[14*n_w+2*i] * H_real + v[14*n_w+1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C9(x)
        H_real, H_imag = Hess_CV(x, i, n_xj, Ztr, 6, 7, 8, 9, 18, 19)
        nl_hess = nl_hess + v[16*n_w+2*i] * H_real + v[16*n_w+1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C10(x)
        H_real, H_imag = Hess_CI(x, i, n_xj, Ytr, Yl5[i], reac_comb[4], 8, 9, 18, 19, 20, 21, ind_reac5)
        nl_hess = nl_hess + v[18*n_w+2*i] * H_real + v[18*n_w+1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C11(x)
        H_real, H_imag = Hess_CV(x, i, n_xj, Zg, 8, 9, -1, -1, 20, 21)
        nl_hess = nl_hess + v[20*n_w+2*i] * H_real + v[20*n_w+1+2*i] * H_imag
        
        # Derivadas parciais jacobiana da restrição C12(x)
        Hess = Hess_C12(x, i, n_xj)
        nl_hess = nl_hess + v[22*n_w+i] * Hess
    
    return nl_hess

def objective_function(x, PowfN_pu, Sbase, Towf, Ce, Koff, Poff, Kmid, Pmid, Kon, Pon, reac_comb, pw, Closs_max, Creac_max, wl, wr, n_w, n_xj, n_Y):
    """
    Calculate the objective function value of the problem
    :param x: vector of the variables solution
    :param PowfN_pu: active power generated by the OWPP in pu
    :param Sbase: base power value in MVA
    :param Towf: life time of the WOPP in years 
    :param Ce: cost of energy in u.m./MWh
    :param Koff, Kmid, Kon, Poff, Pmid, Pon: cost coefficients for offshore, mid-cable, and onshore reactors
    :param pw: probability occurrence of generated active power
    :param reac_comb: reactor combination under evaluation
    :param Closs_max, Creac_max: maximum value to active power losses and reactor placed
    :param n_w: quantity of active power generation points to evaluate
    :param n_Y: quantity of reactors to be aallocated
    :param wl, wr: weighs of the objective function
    :param n_xj: length of x vector for each n_w
    :return totalCost: normalized objective function value
    """   
    Umod, Utheta, Imod, Itheta, Yl_x, Yreac_x = identify_x(x, n_w, n_xj, n_Y)
    
    Yreac = np.zeros(len(reac_comb))
    Yreac[reac_comb] = Yreac_x
    
    U5 = Umod[0:,4] * np.exp(Utheta[0:,4] * 1j)    
    Ig = Imod[0:,5] * np.exp(Itheta[0:,5] * 1j)
        
    plossAC = acLosses(PowfN_pu, U5, Ig, Sbase) * pw
    ClossAC = lossesCost(Towf, Ce, plossAC)
    
    if Yreac[0] != 0:
        Creact1 = -(Koff * Yreac[0] * Sbase) + Poff
    else:
        Creact1 = 0
    if Yreac[1] != 0:    
        Creact2 = -(Koff * Yreac[1] * Sbase) + Poff
    else:
        Creact2 = 0
    if Yreac[2] != 0: 
        Creact3 = -(Kmid * Yreac[2] * Sbase) + Pmid
    else:
        Creact3 = 0
    if Yreac[3] != 0:         
        Creact4 = -(Kon * Yreac[3] * Sbase) + Pon
    else:
        Creact4 = 0
    if Yreac[4] != 0:     
        Creact5 = -(Kon * Yreac[4] * Sbase) + Pon
    else:
        Creact5 = 0
    
    totalCost = wl * (np.sum(ClossAC) / Closs_max) + wr * ((Creact1 + Creact2 + Creact3 + Creact4 + Creact5) / Creac_max)
    
    return totalCost

def of_jac(x, PowfN_pu, Sbase, Towf, Ce, Koff, Poff, Kmid, Pmid, Kon, Pon, reac_comb, pw, Closs_max, Creac_max, wl, wr, n_w, n_xj, n_Y):
    """
    Calculate the jacobian vector with the partial derivative values of the objective function
    :param x: vector of the variables solution
    :param PowfN_pu: active power generated by the OWPP in pu
    :param Sbase: base power value in MVA
    :param Towf: life time of the WOPP in years 
    :param Ce: cost of energy in u.m./MWh
    :param Koff, Kmid, Kon, Poff, Pmid, Pon: cost coefficients for offshore, mid-cable, and onshore reactors
    :param pw: probability occurrence of generated active power
    :param reac_comb: reactor combination under evaluation
    :param Closs_max, Creac_max: maximum value to active power losses and reactor placed
    :param n_w: quantity of active power generation points to evaluate
    :param n_Y: quantity of reactors to be aallocated
    :param wl, wr: weighs of the objective function
    :param n_xj: length of x vector for each n_w
    :return jac_of: jacobian vector of the objective function
    """   
    if n_w == 1:
        Closs = np.array([wl*8760*Towf*Ce*Sbase*pw/Closs_max])
    else:
        Closs = wl*8760*Towf*Ce*Sbase*pw/Closs_max

    jac_of = np.zeros_like(x)
    for i in range(n_w):
        jac_of[8+n_xj*i] = -x[20+n_xj*i] * np.cos(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        jac_of[9+n_xj*i] = x[8+n_xj*i] * x[20+n_xj*i] * np.sin(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        jac_of[20+n_xj*i] = -x[8+n_xj*i] * np.cos(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        jac_of[21+n_xj*i] = -x[8+n_xj*i] * x[20+n_xj*i] * np.sin(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        
    if reac_comb[0]:
        Creact1 = -wr*Koff*Sbase/Creac_max
    else:
        Creact1 = 0
    if reac_comb[1]:    
        Creact2 = -wr*Koff*Sbase/Creac_max
    else:
        Creact2 = 0
    if reac_comb[2]: 
        Creact3 = -wr*Kmid*Sbase/Creac_max
    else:
        Creact3 = 0
    if reac_comb[3]:         
        Creact4 = -wr*Kon*Sbase/Creac_max
    else:
        Creact4 = 0
    if reac_comb[4]:     
        Creact5 = -wr*Kon*Sbase/Creac_max
    else:
        Creact5 = 0    
    Creac = np.array([Creact1, Creact2, Creact3, Creact4, Creact5])
    ind_del = np.where(Creac == 0)[0]
    Creac = np.delete(Creac,ind_del)
    if Creac.any():
        jac_of[-n_Y:] = Creac
    else:
        jac_of[-n_Y:] = 0
   
    return jac_of

def of_hess(x, PowfN_pu, Sbase, Towf, Ce, Koff, Poff, Kmid, Pmid, Kon, Pon, reac_comb, pw, Closs_max, Creac_max, wl, wr, n_w, n_xj, n_Y):
    """
    Calculate the hessian matrix with the second ordem partial derivative values of the objective function
    :param x: vector of the variables solution
    :param PowfN_pu: active power generated by the OWPP in pu
    :param Sbase: base power value in MVA
    :param Towf: life time of the WOPP in years 
    :param Ce: cost of energy in u.m./MWh
    :param Koff, Kmid, Kon, Poff, Pmid, Pon: cost coefficients for offshore, mid-cable, and onshore reactors
    :param pw: probability occurrence of generated active power
    :param reac_comb: reactor combination under evaluation
    :param Closs_max, Creac_max: maximum value to active power losses and reactor placed
    :param n_w: quantity of active power generation points to evaluate
    :param n_Y: quantity of reactors to be aallocated
    :param wl, wr: weighs of the objective function
    :param n_xj: length of x vector for each n_w
    :return hess_of: hessian matrix of the objective function
    """       
    if n_w == 1:
        Closs = np.array([wl*8760*Towf*Ce*Sbase*pw/Closs_max])
    else:
        Closs = wl*8760*Towf*Ce*Sbase*pw/Closs_max
    hess_of = np.diag(np.zeros_like(x))
    for i in range(n_w):        
        hess_of[8+n_xj*i,9+n_xj*i] = x[20+n_xj*i] * np.sin(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[8+n_xj*i,20+n_xj*i] = -np.cos(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[8+n_xj*i,21+n_xj*i] = -x[20+n_xj*i] * np.sin(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[9+n_xj*i,8+n_xj*i] = x[20+n_xj*i] * np.sin(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[9+n_xj*i,9+n_xj*i] = x[8+n_xj*i] * x[20+n_xj*i] * np.cos(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[9+n_xj*i,20+n_xj*i] = x[8+n_xj*i] * np.sin(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[9+n_xj*i,21+n_xj*i] = -x[8+n_xj*i] * x[20+n_xj*i] * np.cos(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[20+n_xj*i,8+n_xj*i] = -np.cos(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[20+n_xj*i,9+n_xj*i] = x[8+n_xj*i] * np.sin(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[20+n_xj*i,21+n_xj*i] = -x[8+n_xj*i] * np.sin(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[21+n_xj*i,8+n_xj*i] = -x[20+n_xj*i] * np.sin(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[21+n_xj*i,9+n_xj*i] = -x[8+n_xj*i] * x[20+n_xj*i] * np.cos(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[21+n_xj*i,20+n_xj*i] = -x[8+n_xj*i] * np.sin(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
        hess_of[21+n_xj*i,21+n_xj*i] = x[8+n_xj*i] * x[20+n_xj*i] * np.cos(x[9+n_xj*i]-x[21+n_xj*i])*Closs[i]
    return hess_of

def identify_x(x, n_w, n_xj, n_Y):
    """
    Identify the interest variables on the x vector
    :param x: vector of the variables solution   
    :param n_w: quantity of active power generation points to evaluate
    :param n_Y: quantity of reactors to be aallocated
    :param n_xj: length of x vector for each n_w
    :return Umod, Utheta, Imod, Itheta, Yl_x, Yreac_x: voltage, current and reactor optimized results
    """         
    n_x = len(x)    
    Yreac_x = x[-n_Y:]    
    
    xn = np.delete(x,np.arange(n_x-n_Y, n_x))
    
    Umod = np.ones((n_w,5))
    Utheta = np.ones((n_w,5))
    Imod = np.ones((n_w,6))
    Itheta = np.ones((n_w,6))
    Yl_x = np.zeros((n_w,n_Y))
    
    for i in range(n_w):
        Umod[i,0] = xn[0+n_xj*i]
        Umod[i,1] = xn[2+n_xj*i]
        Umod[i,2] = xn[4+n_xj*i]
        Umod[i,3] = xn[6+n_xj*i]
        Umod[i,4] = xn[8+n_xj*i]
        Utheta[i,0] = xn[1+n_xj*i]
        Utheta[i,1] = xn[3+n_xj*i]
        Utheta[i,2] = xn[5+n_xj*i]
        Utheta[i,3] = xn[7+n_xj*i]
        Utheta[i,4] = xn[9+n_xj*i]
        Imod[i,0] = xn[10+n_xj*i]
        Imod[i,1] = xn[12+n_xj*i]
        Imod[i,2] = xn[14+n_xj*i]
        Imod[i,3] = xn[16+n_xj*i]
        Imod[i,4] = xn[18+n_xj*i]
        Imod[i,5] = xn[20+n_xj*i]
        Itheta[i,0] = xn[11+n_xj*i]
        Itheta[i,1] = xn[13+n_xj*i]
        Itheta[i,2] = xn[15+n_xj*i]
        Itheta[i,3] = xn[17+n_xj*i]
        Itheta[i,4] = xn[19+n_xj*i]
        Itheta[i,5] = xn[21+n_xj*i]
        Yl_x[i,0] = xn[22+n_xj*i]
        if n_Y > 1:
            Yl_x[i,1] = xn[23+n_xj*i]
        if n_Y > 2:
            Yl_x[i,2] = xn[24+n_xj*i]
        if n_Y > 3:
            Yl_x[i,3] = xn[25+n_xj*i]
        if n_Y > 4:
            Yl_x[i,4] = xn[26+n_xj*i]
       
    return Umod, Utheta, Imod, Itheta, Yl_x, Yreac_x